# Generated by Django 4.0.4 on 2022-05-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id de producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('imagen_producto', models.ImageField(default='', upload_to='images/productos', verbose_name='imagen del producto')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado del producto')),
            ],
        ),
    ]
