# Generated by Django 4.0.4 on 2022-06-11 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websolicitudservicio',
            name='nro_factura',
            field=models.ForeignKey(blank=True, db_column='nrofac', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='core.webfactura'),
        ),
        migrations.AlterField(
            model_name='webfactura',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto'),
        ),
    ]
