# Generated by Django 4.0.5 on 2022-06-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_websolicitudservicio_nro_factura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websolicitudservicio',
            name='acepta_fecha_hora_solicitada',
        ),
        migrations.AlterField(
            model_name='websolicitudservicio',
            name='estado_ss',
            field=models.CharField(blank=True, choices=[('P', 'Pendiente'), ('A', 'Fecha Visita Aceptada'), ('MC', 'Fecha modificada cliente'), ('M', 'Fecha Modificada'), ('FVA', 'Fecha de visita acordada'), ('SR', 'Servicio Realizado')], default='P', max_length=3, null=True),
        ),
    ]
